version: "3.2"

volumes:
  db:

services:
  app:
    build: .
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    ports:
      - "3007:3000"
    depends_on:
      - db

  db:
    image: mongo
    volumes:
     - db:/data/db
    ports:
      - "27017:27017"

